version: '3.8'
services:
 mysql:
  image: mysql:8
  container_name: mysql
  command: mysqld --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
   MYSQL_DATABASE: 'morbidgenes_db'
   MYSQL_USER: 'bernt'
   MYSQL_PASSWORD: 'morbidgenes-db'
   MYSQL_ROOT_PASSWORD: 'morbidgenes-db'
  ports:
   - "9918:3306"
  volumes:
   - /home/MorbidGenes/00_DEV/morbidgenes/db/morbidgenes_db/data/mysql/:/var/lib/mysql/