version: '3.8'
services:
 mysql:
  image: mysql:8
  container_name: morbidgenes_mysql
  command: mysqld --default-authentication-plugin=mysql_native_password
  restart: always
  environment:
   MYSQL_DATABASE: 'morbidgenes_db'
   MYSQL_USER: 'bernt'
   MYSQL_PASSWORD: 'morbidgenes-db'
   MYSQL_ROOT_PASSWORD: 'morbidgenes-db'
  ports:
   - "9918:3306"
  volumes:
   - /home/morbidgenes/morbidgenes_db/data/mysql/:/var/lib/mysql/
 api:
  build: ./api/
  container_name: morbidgenes_api
  command: Rscript /morbidgenes_api_volume/start_morbidgenes-db_api.R
  restart: always
  volumes:
  - /home/morbidgenes/morbidgenes_db/api/:/morbidgenes_api_volume/
  ports:
     - "10908-10917:10918"
  environment:
   PASSWORD: 'morbidgenes-db'
 alb:
  image: 'dockercloud/haproxy'
  links:
     - api
  volumes:
     - /var/run/docker.sock:/var/run/docker.sock
  restart: always
 app:
  build: ./app/
  container_name: morbidgenes_app
  restart: always
  ports:
     - "80:80"
     - "443:443"
volumes:
 morbidgenes_api_volume: