default:
  morbidgenes_db_local:
    dbtype: mysql
    dbname: morbidgenes_db
    user: bernt
    password: "morbidgenes-db"
    server: "0.0.0.0"
    host: "127.0.0.1"
    port: "9918"
    port_self: "10918"
    secret: QSnDcVt'Lg:8G+Q9LB,grz-~)tiZ|kr|X4m6nAd?'Pxv;w9PN9.uu$93a;9<PA4
    refresh: 360
  morbidgenes_db:
    dbtype: mysql
    dbname: morbidgenes_db
    user: bernt
    password: "morbidgenes-db"
    server: "0.0.0.0"
    host: "morbidgenes_mysql"
    port: "9918"
    port_self: "10918"
    secret: QSnDcVt'Lg:8G+Q9LB,grz-~)tiZ|kr|X4m6nAd?'Pxv;w9PN9.uu$93a;9<PA4
    refresh: 3600
